"""
File: abstractcollection.py
Author: Ken Lambert
Editor: Leigh Stauffer
Project 9

"""

class AbstractCollection(object):
    """An abstract collection implementation."""

    # Constructor
    def __init__(self, sourceCollection = None):
        """Sets the initial state of self, which includes the
        contents of sourceCollection, if it's present."""
        self._size = 0
        if sourceCollection:
            for item in sourceCollection:
                self.add(item)

    # Accessor methods
    def isEmpty(self):
        """Returns True if len(self) == 0, or False otherwise."""
        return len(self) == 0
    
    def __len__(self):
        """Returns the number of items in self."""
        return self._size

    def __str__(self):
        """Returns the string representation of self, using []
        as delimiters."""
        return "[" + ", ".join(map(str, self)) + "]"

    def __eq__(self, other):
        """Returns True if self equals other,
        or False otherwise.
        Compares pairs of items in the two sequences
        generated by the iterators on self and other."""
        if self is other: return True
        if type(self) != type(other) or \
           len(self) != len(other):
            return False
        otherIter = iter(other)
        for item in self:
            if item != next(otherIter):
                return False
        return True

    def __add__(self, other):
        """Returns a new collection containing the contents
        of self and other."""
        result = type(self)(self)
        for item in other:
            result.add(item)
        return result

    def count(self, item):
        """Returns the number of instance of item in self."""
        counter = 0
        for nextItem in self:
            if item == nextItem: counter += 1
        return counter


